name: MLflow CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Start job
        run: echo start

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.7

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12.7
          auto-activate-base: false

      - name: Initialize Conda
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda --version

      - name: Install MLflow
        run: |
          source $CONDA/etc/profile.d/conda.sh
          pip install mlflow

      - name: Run MLflow Project
        env:
          MLFLOW_TRACKING_URI: file:${{ github.workspace }}/mlruns
        run: |
          source $CONDA/etc/profile.d/conda.sh
          mlflow run MLProject

      - name: Read MLflow run id
        run: |
          RUN_ID=$(cat MLProject/run_id.txt)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts-${{ env.RUN_ID }}
          path: mlruns

      - name: Build Docker image from MLflow model
        env:
          MLFLOW_TRACKING_URI: file:${{ github.workspace }}/mlruns
        run: |
          source $CONDA/etc/profile.d/conda.sh
          mlflow models build-docker -m runs:/${{ env.RUN_ID }}/model -n mlflow-loan-model

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Tag Docker image as latest
        run: docker tag mlflow-loan-model ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-loan-model:latest

      - name: Push Docker image latest
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-loan-model:latest

      - name: End job
        run: echo done