name: MLflow CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo start

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.7

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12.7
          auto-activate-base: false

      - name: Initialize Conda
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda --version

      - name: Install MLflow
        run: pip install mlflow

      - name: Run mlflow project
        run: |
          source $CONDA/etc/profile.d/conda.sh
          mlflow run MLProject

      - name: Get latest MLflow run id
        run: |
          source $CONDA/etc/profile.d/conda.sh
          echo "RUN_ID=$(mlflow runs list --experiment-id 0 --order-by attributes.start_time DESC --max-results 1 | tail -n 1 | awk '{print $1}')" >> $GITHUB_ENV

      - name: Save MLflow artifacts to repository
        run: |
          mkdir -p ci_artifacts/${{ env.RUN_ID }}
          cp -r mlruns ci_artifacts/${{ env.RUN_ID }}

      - name: Commit MLflow artifacts
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add ci_artifacts
          git commit -m "Add MLflow artifacts for run ${{ env.RUN_ID }}" || echo "No changes"
          git push

      - name: Build Docker Model
        run: |
          source $CONDA/etc/profile.d/conda.sh
          mlflow models build-docker -m runs:/${{ env.RUN_ID }}/model -n mlflow-loan-model

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Tag Docker Image
        run: docker tag mlflow-loan-model ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-loan-model:latest

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-loan-model:latest

      - name: Complete job
        run: echo done